### PR TITLE
Updated all instances of Jitsi to Leaf and updated base URL to meet.modesttree.com

### PR DESCRIPTION
**Pull request by mtamoussa**

### CODE REVIEW

**Review by mwamboldtMT — CHANGES_REQUESTED** [review]
There are a bunch of binary files getting checked in to the installers folder that are probably not meant to be.

**Comment by mtamoussa** [comment]
> There are a bunch of binary files getting checked in to the installers folder that are probably not meant to be.

Could that be because of me changing a whole bunch of config files and when it rebuilt it generated binary files or something?

**Comment by mwamboldtMT** [comment]
Yes, Honestly that whole installers folder doesn't make sense for our use, that would be downloading their installer and running it

**Comment by mtamoussa** [comment]
I originally left the installers folder untouched, but when Sam tried to install it, the installer still had Jitsi branding. So all the changes there are for rebranding the installation process itself. If we are going to forgo that I'm not sure what else we can use or how to go about it.

**Review by mwamboldtMT — APPROVED** [review]

**Pull request merged**
